# docker-compose.yml

version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - redisnet
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - static_volume:/arc/static  # <-- bind the static volume
      - media_volume:/arc/media  # <-- bind the media volume
    ports:
      - "8000:8000"
    networks:
      - webnet
      - redisnet
      - nginx_network
    links:
      - redis

  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - .:/arc
      - static_volume:/arc/static  # <-- bind the static volume
      - media_volume:/arc/media  # <-- bind the media volume
    ports:
      - 1914:80
    depends_on:
      - web
    networks:  # <-- here
      - nginx_network
networks:
  nginx_network:
    driver: bridge
  webnet:
    driver: bridge
  redisnet:
    driver: bridge

volumes:
    static_volume:
    media_volume: