# docker-compose.yml

version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - redisnet
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - webnet
      - redisnet
    links:
      - redis

networks:
  webnet:
  redisnet: